/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagement;

import java.awt.Toolkit;

/**
 *
 * @author Gaurav Sehar
 */
public class AboutGauravSehar extends javax.swing.JFrame {

    /**
     * Creates new form AboutGauravSehar
     */
    public AboutGauravSehar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GSLogo = new javax.swing.JLabel();
        ForceLike = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About Developer");
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(SplashScreen.class.getResource("/default_icons/AppIcon.png")));
        setUndecorated(true);

        GSLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_icons/GSLogo.png"))); // NOI18N

        ForceLike.setBackground(new java.awt.Color(0, 0, 0));
        ForceLike.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ForceLike.setText("I like this Project");
        ForceLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForceLikeActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("About Section : \t\t                         [Scroll for More Info.]\nIt is a Minor Project, Submitted to Payal Mam & Rajiv Chopra Sir.\nProgrammer, Designer :   Gaurav Sehar (CSE1) 3rd Year\nEnrollment No. :                01913202715\nInstitution :                         Guru Tegh Bahadur Institute of Technology\n\nThis Application Requires MySQL Server with Gaurav_Sehar_CMS\ndatabase initialized with 'root' user having 'sehar' as password.\n\nAll icons are designed by the Gaurav Sehar for purpose of this\napplication, Using Adobe illustrator and Photoshop from scratch.\n\nJava Mail API requires working internet connection, However it is\nnow depreciated due to lack of security measures.\n\n-----Libraries Used ----------------------------------------------------\nactivation.jar\nbeansbinding-1.2.1.jar\nderby.jar\neclipselink.jar\njavax.persistence_2.1.0.v201304241213.jar\njava_mail.jar\nmysql-connector-java-5.0.8-bin\norg.eclipse.persistence.jpa.jpql_2.5.2.v20140319-9ad6abd.jar\nswingx-all-1.6.4.jar");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setCaretPosition(0);
        jTextArea1.setMaximumSize(new java.awt.Dimension(370, 112));
        jTextArea1.setPreferredSize(new java.awt.Dimension(220, 400));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(GSLogo)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ForceLike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GSLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForceLike)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForceLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForceLikeActionPerformed
        this.dispose();
    }//GEN-LAST:event_ForceLikeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForceLike;
    private javax.swing.JLabel GSLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
