/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav Sehar
 */
public class Password_Forgot extends javax.swing.JFrame {

    /**
     * Creates new form Password_Forgot
     */
    public Password_Forgot() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailField = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        CloseImg = new javax.swing.JLabel();
        SendButton = new javax.swing.JButton();
        TitleDescriptionLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        DescriptionTextArea = new javax.swing.JTextArea();
        Back = new javax.swing.JLabel();
        BackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Recovery");
        setIconImage(Toolkit.getDefaultToolkit().getImage(SplashScreen.class.getResource("/default_icons/AppIcon.png")));
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setUndecorated(true);
        setResizable(false);

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleLabel.setText("Password Recovery");
        TitleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitleLabelMouseClicked(evt);
            }
        });

        CloseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_icons/Close.png"))); // NOI18N
        CloseImg.setMaximumSize(new java.awt.Dimension(20, 25));
        CloseImg.setMinimumSize(new java.awt.Dimension(20, 25));
        CloseImg.setPreferredSize(new java.awt.Dimension(20, 25));
        CloseImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseImgMouseClicked(evt);
            }
        });

        SendButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        TitleDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TitleDescriptionLabel.setText("Using Email");

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UsernameLabel.setText("Email ID");

        DescriptionTextArea.setEditable(false);
        DescriptionTextArea.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        DescriptionTextArea.setRows(5);
        DescriptionTextArea.setText("Reset password will be send on the email which was provided\nduring registration");
        DescriptionTextArea.setFocusable(false);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_icons/Back.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        BackLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackLabel.setText("Back");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriptionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitleDescriptionLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmailField)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UsernameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(SendButton)
                        .addContainerGap(168, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CloseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TitleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DescriptionTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseImgMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseImgMouseClicked

    private void BackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseClicked
        this.dispose();
        JFrame SignIn = new SignIn();
        SignIn.setVisible(true);
    }//GEN-LAST:event_BackLabelMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        this.dispose();
        JFrame SignIn = new SignIn();
        SignIn.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        UsersDatabaseHandler uDB = new UsersDatabaseHandler();
        String s = uDB.ValidateUserEmail(EmailField.getText().trim());
        if(!s.equals("NOT FOUND")){
            GMail.SendMail(EmailField.getText().trim(), "Password Recovery Mail by GS College Management", "Your Password for Login is : " + s);
            JOptionPane.showMessageDialog(null, "Email Sent.\nCheck your inbox.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Email not Found in Database", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SendButtonActionPerformed

    private void TitleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleLabelMouseClicked
        if(JOptionPane.showInputDialog(null, "You have clicked a hidden menu button to drop all databases made by this application in past executions."
                + "\nEnter Password to Continue", "Hidden Button Clicked !!!", JOptionPane.INFORMATION_MESSAGE).equals("qazpl,")
        ){
            UsersDatabaseHandler uDB = new UsersDatabaseHandler();
            StudentsDatabaseHandler sDB = new StudentsDatabaseHandler();
            FacultyDatabaseHandler fDB = new FacultyDatabaseHandler();
            uDB.UserDBDestroy(); sDB.StudentDBDestroy(); fDB.FacultyDBDestroy();
            uDB.CloseDB(); sDB.CloseDB(); fDB.CloseDB();
            GS_GarbageCollector.Destroy();
            JOptionPane.showMessageDialog(null, "Application will close now.", "Information", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_TitleLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel CloseImg;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel TitleDescriptionLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
