/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav Sehar
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        UsersDatabaseHandler uDB = new UsersDatabaseHandler();
        uDB.UserDBInitializer();
        uDB.CloseDB();
        StudentsDatabaseHandler sDB = new StudentsDatabaseHandler();
        sDB.StudentDBInitializer();
        sDB.CloseDB();
        FacultyDatabaseHandler fDB = new FacultyDatabaseHandler();
        fDB.FacultyDBInitializer();
        fDB.CloseDB();
        initComponents();
        ForgotPassLabel.setText("<html><u>Fo</u>rg<u>ot Password</u></html>");
        this.getContentPane().setBackground(Color.WHITE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);        
    }
    
    private boolean validator(){
        boolean uName = UsernameField.getText().equals("admin");
        boolean uPass = String.valueOf(PasswordField.getPassword()).equals("gs");
        if(uName == true && uPass == true){
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        CloseImg = new javax.swing.JLabel();
        TitleDescriptionLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ForgotPassLabel = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign in to Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setIconImage(Toolkit.getDefaultToolkit().getImage(SplashScreen.class.getResource("/default_icons/AppIcon.png")));
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 280));
        setResizable(false);

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TitleLabel.setText("Sign in");

        CloseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_icons/Close.png"))); // NOI18N
        CloseImg.setMaximumSize(new java.awt.Dimension(20, 25));
        CloseImg.setMinimumSize(new java.awt.Dimension(20, 25));
        CloseImg.setPreferredSize(new java.awt.Dimension(20, 25));
        CloseImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseImgMouseClicked(evt);
            }
        });

        TitleDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TitleDescriptionLabel.setText("Using Credentials Provided");

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UsernameLabel.setText("Username");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordLabel.setText("Password");

        ForgotPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ForgotPassLabel.setText("Forgot Password");
        ForgotPassLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ForgotPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassLabelMouseClicked(evt);
            }
        });

        ContinueButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(TitleDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameField)
                            .addComponent(PasswordField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernameLabel)
                                    .addComponent(PasswordLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ForgotPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(ContinueButton)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel)
                    .addComponent(CloseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleDescriptionLabel)
                .addGap(18, 18, 18)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ForgotPassLabel)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContinueButton)
                        .addGap(17, 17, 17))))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseImgMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseImgMouseClicked

    private void ForgotPassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassLabelMouseClicked
        JFrame Password_Forgot = new Password_Forgot();
        Password_Forgot.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ForgotPassLabelMouseClicked

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        UsersDatabaseHandler uDB = new UsersDatabaseHandler();
//        if(validator()){
//            JFrame Dashboard = new Dashboard();
//            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//            Dashboard.getContentPane().setBackground(Color.WHITE);
//            Dashboard.setLocation(dim.width/2-Dashboard.getSize().width/2, dim.height/2-Dashboard.getSize().height/2);
//            Dashboard.setVisible(true);
//            this.dispose();
//        }
//        else{
            if(uDB.ValidateUser(UsernameField.getText(), String.valueOf(PasswordField.getPassword()))){
                JFrame Dashboard = new Dashboard();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                Dashboard.getContentPane().setBackground(Color.WHITE);
                Dashboard.setLocation(dim.width/2-Dashboard.getSize().width/2, dim.height/2-Dashboard.getSize().height/2);
                Dashboard.setVisible(true);
                this.dispose();
                uDB.CloseDB();
            }
            else{
                JOptionPane.showMessageDialog(null, "Username or Password is Incorrect", "Error", JOptionPane.ERROR_MESSAGE);
            }
//        }
        uDB.CloseDB();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame SignIn = new SignIn();
                SignIn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseImg;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel ForgotPassLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel TitleDescriptionLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
